### ISSUE TITLE
Use GitHub token for workflows that get rate-limited by GitHub.

### ISSUE THREAD

**Issue by Joaqim** [joaqim/dotfiles#60]
Consider adding `access-tokens` where needed.
```yml
  - name: Install Nix
    uses: cachix/install-nix-action@v17
      with:
          extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
```
